<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd"
             version="2.2">

    <persistence-unit name="AdeptJ_PU" transaction-type="RESOURCE_LOCAL">

        <!-- JPA Entities -->
        <class>com.adeptj.modules.data.jpa.entity.User</class>

        <exclude-unlisted-classes>true</exclude-unlisted-classes>

        <properties>
            <property name="javax.persistence.jdbc.driver" value="com.mysql.cj.jdbc.Driver"/>
            <property name="javax.persistence.jdbc.url"
                      value="jdbc:mysql://localhost:3306/AdeptJ?useSSL=false&amp;nullNamePatternMatchesAll=true&amp;allowPublicKeyRetrieval=true"/>
            <property name="javax.persistence.jdbc.user" value="ut"/>
            <property name="javax.persistence.jdbc.password" value="EclipseLink@2018"/>
            <property name="eclipselink.ddl-generation" value="create-or-extend-tables"/>
            <property name="eclipselink.ddl-generation.output-mode" value="both"/>
            <property name="eclipselink.logging.file" value="jpa.log"/>
            <property name="eclipselink.logging.level" value="FINEST"/>
            <property name="eclipselink.exception-handler" value="com.adeptj.modules.data.jpa.JpaExceptionHandler"/>
        </properties>

    </persistence-unit>

</persistence>
